import { createRoot } from 'react-dom/client'
import '@fontsource/bricolage-grotesque/500.css'
import '@fontsource/bricolage-grotesque/700.css'
import '@fontsource/bricolage-grotesque/800.css'
import '@fontsource/figtree/400.css'
import '@fontsource/figtree/500.css'
import '@fontsource/figtree/600.css'
import '@fontsource/figtree/700.css'
import '@fontsource/figtree/800.css'
import '@fontsource/jetbrains-mono/400.css'
import '@fontsource/jetbrains-mono/600.css'
import '@fontsource/jetbrains-mono/700.css'
import '@fontsource/archivo-black/400.css'
import '@fontsource/instrument-serif/400.css'
import './styles.css'
import { App } from './App'
import { RenderStage } from './RenderStage'

createRoot(document.getElementById('root')!).render(location.hash === '#render' ? <RenderStage /> : <App />)
